# Site settings
title: Subtly Chaotic
header-img: img/home-bg.png
email: yellow.khaos@gmail.com
copyright_name: thekevinhuang
description: > # this means to ignore newlines until "baseurl:"
  Fighting entropy one line at a time.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: khaosnrg
github_username:  thekevinhuang
learn_profile: thekevinhuang
email_username: yellow.khaos@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
